language: c
compiler:
  - gcc
  - clang
script: ./scripts/travis-build.sh
notifications:
    irc:
        channels:
          - "irc.freenode.org#tenyr"
        use_notice: true
        skip_join: true
