language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_install:
  - sudo pip install cpp-coveralls
script: "make lockfile= GCOV=1 V=1 SDL=0 && make lockfile= check && make lockfile= local-install"
after_success:
  - coveralls --include src --gcov-options '\-lp'
notifications:
    irc:
        channels:
          - "irc.freenode.org#tenyr"
        use_notice: true
        skip_join: true
