language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_install:
  - sudo pip install cpp-coveralls
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl2-image-dev
script: "make GCOV=1 V=1 && make check && make local-install"
after_success:
  - coveralls --include src --gcov-options '\-lp'
notifications:
    irc:
        channels:
          - "irc.freenode.org#tenyr"
        use_notice: true
        skip_join: true
