language: c
compiler:
  - gcc
  - clang
script: "make MAKE_VERBOSE=1 SDL=0"
notifications:
    irc:
        channels:
          - "irc.freenode.org#tenyr"
        use_notice: true
        skip_join: true
