language: c
compiler:
  - gcc
  - clang
script: "make V=1 SDL=0 && make check && make install"
notifications:
    irc:
        channels:
          - "irc.freenode.org#tenyr"
        use_notice: true
        skip_join: true
