env:
  global:
    - secure: "aue8fIHP0tllE3WR/3bGHke88tkWkLpPGFCPrWQsWvLHEZmIG7ARmZEuhT81JoUldfkoKbJed899qUv/6hHSrzz8mI5KdDrh31lTUdV7kBn7du7I1RmOZenU15Inmx3vhw8+x6AQtR3/CDs/G1RLhsJBjL3EnWUPPjwUt/wT/Ow="
language: c
matrix:
  include:
    - compiler: "gcc-win64"
      env: PLATFORM=mingw BITS=64 HOST=x86_64 CHECK_RULE=check_sw GCOV=  JIT=0 SDL=0
    - compiler: "gcc-win32"
      env: PLATFORM=mingw BITS=32 HOST=i686   CHECK_RULE=check_sw GCOV=  JIT=0 SDL=0
    - compiler: "clang"
      env: PLATFORM=linux BITS=64 HOST=x86_64 CHECK_RULE=check    GCOV=
    - compiler: "gcc"
      env:
        -  PLATFORM=linux BITS=64 HOST=x86_64 CHECK_RULE=check    GCOV=1
        - COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG"
        - COVERITY_SCAN_BRANCH_PATTERN="coverity_scan"
        - COVERITY_SCAN_NOTIFICATION_EMAIL="coverity@tenyr.info"
        - COVERITY_SCAN_BUILD_COMMAND="make V=1 all"
        - COVERITY_SCAN_BUILD_COMMAND_PREPEND=""
os:
  - linux
  - osx
install:
  - sudo -H pip install cpp-coveralls
  - sudo add-apt-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl2 libsdl2-dev libsdl2-image libsdl2-image-dev
  - |
    if [[ $PLATFORM = mingw* ]] ; then
      sudo add-apt-repository --yes ppa:tobydox/mingw-x-precise
      sudo apt-get update -qq
      sudo apt-get install -y mingw32 mingw${BITS}-x-binutils mingw${BITS}-x-gcc mingw${BITS}-x-runtime
      sudo apt-get install -y wine
      export MINGW=/opt/mingw$BITS
      export PATH=$MINGW/bin:$PATH
      export CC=$HOST-w64-mingw32-gcc
      export CXX=$HOST-w64-mingw32-g++
    fi
before_script:
  # implement Coverity Scan with before_script instead of addons.coverity_scan
  # to work around too-early quota check by the coverity_scan addon
  - if [[ -n ${!COVERITY_SCAN_*} ]] ; then curl -s 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' | bash || true ; fi
script:
  - make V=1 all
  - make $CHECK_RULE
  - make local-install
  - make gzip zip
after_success:
  # skip untested SPI code for now
  - if [[ -n $GCOV ]] ; then coveralls --exclude-pattern '.*/spi.*' --include src --gcov-options '\-lp' ; fi
  - if [[ -n $GCOV ]] ; then bash <(curl -s https://codecov.io/bash) -g '*/*spi*' -g '*3rdparty/*' -g '*usr/include/*' -g '*/lexer.c' -g '*/parser.c' ; fi
notifications:
  irc:
    channels:
      - "irc.freenode.org#tenyr"
    use_notice: true
    skip_join: true
addons:
  artifacts:
    paths:
      - $(find dist -type f | tr "\n" :)
      - $(ls -1 $(make showbuilddir)/*.{gz,zip} | tr "\n" :)
    target_paths:
      - build/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
      - version/$(git describe --always --tags --match 'v?.?.?*' $TRAVIS_COMMIT)
      - latest/$PLATFORM/$HOST
