language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
script: "make lockfile= V=1 SDL=0 && make lockfile= check && make lockfile= local-install"
notifications:
    irc:
        channels:
          - "irc.freenode.org#tenyr"
        use_notice: true
        skip_join: true
