language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_install:
  - sudo pip install cpp-coveralls
script: "make GCOV=1 V=1 SDL=0 && make SDL=0 check && make SDL=0 local-install"
after_success:
  # exclude SDL until Travis has an OS new enough to use SDL2
  - coveralls --exclude-pattern '.*sdl.*' --include src --gcov-options '\-lp'
notifications:
    irc:
        channels:
          - "irc.freenode.org#tenyr"
        use_notice: true
        skip_join: true
